-- CREATE TABLESPACE
 CREATE TABLESPACE XEDRM5_TABLESPACE
  DATAFILE 'asysdefs.dbf' SIZE 50M
  AUTOEXTEND ON NEXT 4M MAXSIZE UNLIMITED ; 

-- USER SQL
CREATE USER "XEDRM5" IDENTIFIED BY "XEDRM5"  
DEFAULT TABLESPACE "XEDRM5_TABLESPACE"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "XEDRM5" QUOTA UNLIMITED ON "XEDRM5_TABLESPACE";

-- ROLES
GRANT "CONNECT" TO "XEDRM5" ;
GRANT "RESOURCE" TO "XEDRM5" ;

-- SYSTEM PRIVILEGES
