-- CREATE TABLESPACE
 CREATE TABLESPACE XEDRM6_TABLESPACE
  DATAFILE 'xedm_xedrm6.dbf' SIZE 50M
  AUTOEXTEND ON NEXT 4M MAXSIZE UNLIMITED ; 

-- 사용자 생성 중 아래 오류 출력 시 주석처리된 쿼리 실행 (12c 버전 이후 공통 사용자 생성 시 c## 를 붙여야함.) 
-- ORA-65096: 공통 사용자 또는 롤 이름이 부적합합니다.
-- ALTER SESSION SET "_ORACLE_SCRIPT"=true;
 
-- USER SQL
CREATE USER "XEDRM6" IDENTIFIED BY "XEDRM6"  
DEFAULT TABLESPACE "XEDRM6_TABLESPACE"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "XEDRM6" QUOTA UNLIMITED ON "XEDRM6_TABLESPACE";

-- ROLES
GRANT "CONNECT" TO "XEDRM6" ;
GRANT "RESOURCE" TO "XEDRM6" ;
GRANT CREATE VIEW TO "XEDRM6";
GRANT CREATE DATABASE LINK TO XEDRM6;

-- SYSTEM PRIVILEGES
