-----------2020.05.18 대시보드 통계기능 관련 테이블 추가-----------
CREATE TABLE XEDRM5."ES_STATLOGICVOLUME"
  (
    "ELEMENTID" CHAR(16),
    "USERID"    VARCHAR2(256),
    "GROUPID"   VARCHAR2(256),
    "FOLDER"    NUMBER(14,0),
    "DOC"       NUMBER(14,0),
    "FILESIZE"  NUMBER(19,0)
  ) TABLESPACE "XEDRM5_TABLESPACE";
CREATE TABLE XEDRM5."ES_STATPHYVOLUME"
  (
    "VOLUMEID"    CHAR(16),
    "REGDATE"     VARCHAR2(10),
    "USEDSPACE"   NUMBER(14,0),
    "TOTAL"       NUMBER(14,0),
    "USABLESPACE" NUMBER(14,0)
  )  TABLESPACE "XEDRM5_TABLESPACE";
CREATE TABLE XEDRM5."ES_STATSUMMARY"
  (
    "ES_EVENT" VARCHAR2(255),
    "USERID"   VARCHAR2(256),
    "ROLEID"   VARCHAR2(256),
    "SUMMARY"  NUMBER(19,0)
  )  TABLESPACE "XEDRM5_TABLESPACE";

  ALTER TABLE XEDRM5."ES_STATLOGICVOLUME" MODIFY ("FILESIZE" NOT NULL ENABLE);
  ALTER TABLE XEDRM5."ES_STATLOGICVOLUME" MODIFY ("DOC" NOT NULL ENABLE);
  ALTER TABLE XEDRM5."ES_STATLOGICVOLUME" MODIFY ("FOLDER" NOT NULL ENABLE);
  ALTER TABLE XEDRM5."ES_STATLOGICVOLUME" MODIFY ("ELEMENTID" NOT NULL ENABLE);
  ALTER TABLE XEDRM5."ES_STATPHYVOLUME" MODIFY ("USABLESPACE" NOT NULL ENABLE);
  ALTER TABLE XEDRM5."ES_STATPHYVOLUME" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE XEDRM5."ES_STATPHYVOLUME" MODIFY ("USEDSPACE" NOT NULL ENABLE);
  ALTER TABLE XEDRM5."ES_STATPHYVOLUME" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE XEDRM5."ES_STATPHYVOLUME" MODIFY ("VOLUMEID" NOT NULL ENABLE);
  ALTER TABLE XEDRM5."ES_STATSUMMARY" MODIFY ("SUMMARY" NOT NULL ENABLE);
  ALTER TABLE XEDRM5."ES_STATSUMMARY" MODIFY ("ES_EVENT" NOT NULL ENABLE);
  
  -----------2020.06.15 협업룸-----------
  insert into XEDRM5.ASYSELEMENT (ELEMENTID,DESCR,USERSCLASS,ECLASSID,EXPIRATION,UUID,CREATOR,CREATED,MODIFIER,MODIFIED,ACCESSED,TRANSACTION_ID,DELETED,STATUS,PARENTACLID,PATH,FOLDERPATH,PARENTID) values ('Coop            ','Coop','NONE            ','FOLDER          ',null,null,'SUPER',to_date('17/02/10','YY/MM/DD'),'SUPER',to_date('17/01/20','YY/MM/DD'),to_date('17/01/20','YY/MM/DD'),null,0,0,null,'/Coop/','/','SPACE_ROOT      ');

  COMMIT;