CREATE TABLE XEDRM5.SAAS_MAIL (
	MAIL_ID VARCHAR2(20) NULL,
	TENANT_ID VARCHAR2(20) NULL,
	MAIL_SUBJECT VARCHAR2(1000) NULL,
	MAIL_ADDR VARCHAR2(256) NULL,
	MAIL_CONTENT VARCHAR2(4000) NULL,
	MAIL_TYPE VARCHAR2(30) NULL,
	SEND_USER_ID VARCHAR2(20) NULL,
	SEND_DATE DATE NULL,
	MAIL_STATUS VARCHAR2(30) NULL,
	VERIFICATION_CODE VARCHAR2(50) NULL,
	APRV_STATUS_CODE VARCHAR2(30) NULL,
	USER_NM VARCHAR2(128) NULL
) TABLESPACE "XEDRM5_TABLESPACE";



-- DROP TABLE

-- DROP TABLE SAAS_TENANT;

CREATE TABLE XEDRM5.SAAS_TENANT (
	TENANT_TYPE VARCHAR2(256) NULL,
	URL VARCHAR2(256) NULL,
	USERNAME VARCHAR2(256) NULL,
	PASSWD VARCHAR2(256) NULL,
	TENANT_ID VARCHAR2(256) NOT NULL,
	DEMO_START_DATE VARCHAR2(20) NULL,
	DEMO_END_DATE VARCHAR2(20) NULL,
	VOLUME_SIZE NUMBER(38,0) NULL,
	USERS_LIMIT NUMBER(38,0) NULL,
	NONFREE_START_DATE VARCHAR2(20) NULL,
	NONFREE_END_DATE VARCHAR2(20) NULL,
	SUBSCRIPTION VARCHAR2(32) NULL,
	USER_ID VARCHAR2(256) NULL,
	ACTIVE_YN CHAR(1) NOT NULL,
	COMPANY_ID VARCHAR2(256) NULL,
	PAYMENT_ID VARCHAR2(20) NULL,
	DISABLE_DT VARCHAR2(20) NULL,
	REG_DT DATE NULL,
	CHG_DT DATE NULL,
	CONSTRAINT SAAS_TENANT_PKEY PRIMARY KEY (TENANT_ID)
) TABLESPACE "XEDRM5_TABLESPACE";

-- DROP TABLE

-- DROP TABLE SW_APPROVAL;

CREATE TABLE XEDRM5.SW_APPROVAL (
	APRV_ID VARCHAR2(22) NOT NULL,
	APRV_CREATE_DATETIME DATE NULL,
	APRV_CPLT_DATETIME DATE NULL,
	WRITER VARCHAR2(256) NULL,
	DEPT_ID VARCHAR2(22) NULL,
	APRV_CONTENT VARCHAR2(100) NULL,
	WORK_PLACE_ID VARCHAR2(22) NULL,
	WORK_START_TIME VARCHAR2(20) NULL,
	WORK_END_TIME VARCHAR2(20) NULL,
	APRV_TYPE_CODE VARCHAR2(30) NULL,
	WORK_START_DATE VARCHAR2(100) NULL,
	WORK_END_DATE VARCHAR2(100) NULL,
	APRV_STATUS_CODE VARCHAR2(30) NULL,
	WORK_APPLY_YN CHAR(1) NULL,
	POLICY_ID VARCHAR2(22) NULL,
	CONSTRAINT SW_APPROVAL_PKEY PRIMARY KEY (APRV_ID)
) TABLESPACE "XEDRM5_TABLESPACE";


-- DROP TABLE

-- DROP TABLE SW_APRV_LINE;

CREATE TABLE XEDRM5.SW_APRV_LINE (
	APRV_ID VARCHAR2(22) NOT NULL,
	REWRITERID VARCHAR2(256) NOT NULL,
	APRV_COMMENT VARCHAR2(2000) NULL,
	COMPLETEDATE DATE NULL,
	"POSITION" NUMBER(5,0) NULL,
	"TYPE" VARCHAR2(20) NULL,
	APRV_STATUS_CODE VARCHAR2(30) NULL,
	CONSTRAINT SW_APRV_LINE_PKEY PRIMARY KEY (APRV_ID, REWRITERID)
) TABLESPACE "XEDRM5_TABLESPACE";

-- DROP TABLE

-- DROP TABLE SW_CODE;

CREATE TABLE XEDRM5.SW_CODE (
	CODE_ID VARCHAR2(30) NOT NULL,
	CODE_NAME VARCHAR2(100) NULL,
	PARENT_CODE VARCHAR2(30) NULL,
	CODE_TYPE VARCHAR2(2) NULL,
	CREATE_DATE DATE NULL,
	CREATOR VARCHAR2(128) NULL,
	MODIFY_DATE DATE NULL,
	MODIFIER VARCHAR2(128) NULL,
	CODE_ORDER NUMBER(38,0) NULL,
	USE_YN CHAR(1) NULL,
	CODE_REF1 VARCHAR2(100) NULL,
	CODE_REF2 VARCHAR2(100) NULL,
	CODE_REF3 VARCHAR2(100) NULL,
	CODE_KEY VARCHAR2(50) NULL,
	CODE_ENM VARCHAR2(100) NULL,
	CONSTRAINT SW_CODE_PKEY PRIMARY KEY (CODE_ID)
) TABLESPACE "XEDRM5_TABLESPACE";

-- DROP TABLE

-- DROP TABLE SW_COMPANY;

CREATE TABLE XEDRM5.SW_COMPANY (
	COMPANY_ID VARCHAR2(20) NOT NULL,
	COMPANY_NAME VARCHAR2(100) NULL,
	HOMEPAGE VARCHAR2(100) NULL,
	ADDRESS VARCHAR2(100) NULL,
	TEL VARCHAR2(20) NULL,
	ENABLED CHAR(1) NULL,
	LOGO BLOB NULL,
	EMPLOYEE_NUM VARCHAR2(100) NULL,
	CEO_NAME VARCHAR2(100) NULL,
	OFF_WORK_IMAGE VARCHAR2(3000) NULL,
	POLICY_ID VARCHAR2(22) NULL,
	AGT_INCLUDE_PROCESS VARCHAR2(4000) NULL,
	AGT_EXCLUDE_PROCESS VARCHAR2(4000) NULL,
	AGT_LOG_UPLOAD_TYPE NUMBER(38,0) NULL,
	WORK_PLACE_ID VARCHAR2(22) NULL,
	WIZARD_STEP NUMBER(38,0) NULL,
	SW52_GPS_CHECK_YN CHAR(1) NULL,
	CONSTRAINT SW_COMPANY_PKEY PRIMARY KEY (COMPANY_ID)
) TABLESPACE "XEDRM5_TABLESPACE";

-- DROP TABLE

-- DROP TABLE SW_GO_OUT;

CREATE TABLE XEDRM5.SW_GO_OUT (
	USER_ID VARCHAR2(256) NOT NULL,
	WORK_DAY VARCHAR2(20) NOT NULL,
	START_TIME VARCHAR2(20) NULL,
	END_TIME VARCHAR2(20) NULL,
	"TYPE" VARCHAR2(30) NOT NULL,
	STATUS NUMBER(1,0) NOT NULL,
	"CONTENT" VARCHAR2(100) NULL,
	TAG VARCHAR2(512) NULL,
	"YEAR" NUMBER(38,0) NULL,
	WEEK NUMBER(38,0) NULL,
	GOOUT_TIME NUMBER(38,0) NOT NULL,
	DEPT_ID VARCHAR2(256) NOT NULL,
	START_CPUTIME NUMBER(38,0) NOT NULL,
	END_CPUTIME NUMBER(38,0) NOT NULL
) TABLESPACE "XEDRM5_TABLESPACE";

-- DROP TABLE

-- DROP TABLE SW_GROUP;

CREATE TABLE XEDRM5.SW_GROUP (
	GROUP_ID VARCHAR2(256) NOT NULL,
	REG_ID VARCHAR2(256) NULL,
	REG_DT DATE NULL,
	CHG_ID VARCHAR2(256) NULL,
	CHG_DT DATE NULL,
	SW52_ALARM_YN VARCHAR2(1) NULL,
	SW52_PC_LOCK_YN CHAR(1) NULL,
	SW52_PC_SHUTDOWN_YN CHAR(1) NULL,
	SW52_AUTO_COMMUTE_YN CHAR(1) NULL,
	SW52_GPS_CHECK_YN CHAR(1) NULL,
	SW52_POLICY_ID VARCHAR2(22) NULL,
	CONSTRAINT SW_GROUP_PKEY PRIMARY KEY (GROUP_ID)
) TABLESPACE "XEDRM5_TABLESPACE";

-- DROP TABLE

-- DROP TABLE SW_HOLIDAY;

CREATE TABLE XEDRM5.SW_HOLIDAY (
	HOLIDAY VARCHAR2(30) NOT NULL,
	HOLIDAY_NAME VARCHAR2(200) NULL,
	REPEAT_YN CHAR(1) NULL,
	REG_DATE DATE NULL,
	REG_ID VARCHAR2(256) NULL,
	CONSTRAINT SW_HOLIDAY_PKEY PRIMARY KEY (HOLIDAY)
) TABLESPACE "XEDRM5_TABLESPACE";

-- DROP TABLE

-- DROP TABLE SW_NOTICE;

CREATE TABLE XEDRM5.SW_NOTICE (
	TITLE VARCHAR2(100) NULL,
	"CONTENT" VARCHAR2(4000) NULL,
	CREATE_DATETIME DATE NULL,
	MODIFY_DATETIME DATE NULL,
	NOTICE_ID VARCHAR2(22) NOT NULL,
	CREATOR VARCHAR2(256) NULL,
	MODIFIER VARCHAR2(256) NULL,
	CONSTRAINT SW_NOTICE_PKEY PRIMARY KEY (NOTICE_ID)
) TABLESPACE "XEDRM5_TABLESPACE";

-- DROP TABLE

-- DROP TABLE SW_NOTICE_READ;

CREATE TABLE XEDRM5.SW_NOTICE_READ (
	NOTICE_ID VARCHAR2(22) NOT NULL,
	USER_ID VARCHAR2(256) NOT NULL,
	READ_DATETIME DATE NULL,
	CONSTRAINT SW_NOTICE_READ_PKEY PRIMARY KEY (NOTICE_ID, USER_ID)
) TABLESPACE "XEDRM5_TABLESPACE";

-- DROP TABLE

-- DROP TABLE SW_POLICY;

CREATE TABLE XEDRM5.SW_POLICY (
	POLICY_ID VARCHAR2(22) NOT NULL,
	POLICY_TYPE VARCHAR2(22) NULL,
	POLICY_NAME VARCHAR2(100) NULL,
	WORK_START_TIME VARCHAR2(11) NULL,
	WORK_END_TIME VARCHAR2(11) NULL,
	ENABLED CHAR(1) NULL,
	DAY_OF_WEEK VARCHAR2(100) NOT NULL,
	DAY_TYPE VARCHAR2(100) NULL,
	LUNCH_START VARCHAR2(100) NULL,
	LUNCH_END VARCHAR2(100) NULL,
	WORK_PLACE_ID VARCHAR2(20) NULL,
	GPS_CHECK_YN CHAR(1) NULL,
	ABSENCE_TIME NUMBER(7,0) NULL,
	ALARM_TIME VARCHAR2(100) NULL,
	AGT_INCLUDE_PROCESS VARCHAR2(4000) NULL,
	AGT_EXCLUDE_PROCESS VARCHAR2(4000) NULL,
	AGT_LOG_UPLOAD_PERIOD NUMBER(38,0) NULL,
	START_BEFORE_USE_TIME NUMBER(38,0) NULL,
	TEMPORARY_USE_TIME NUMBER(38,0) NULL,
	COMMUTE_RADIUS FLOAT(8) NULL,
	SW52_AUTO_COMMUTE_YN CHAR(1) NULL,
	SW52_PC_LOCK_YN CHAR(1) NULL,
	SW52_PC_SHUTDOWN_YN CHAR(1) NULL,
	SW52_ALARM_YN CHAR(1) NULL,
	SW52_SEND_ALARM_MINS NUMBER(38,0) NULL,
	SW52_PC_COMMUTE_ONLY_YN CHAR(1) NULL,
	DELETED_YN CHAR(1) NULL,
	CONSTRAINT SW_POLICY_PKEY PRIMARY KEY (POLICY_ID, DAY_OF_WEEK)
) TABLESPACE "XEDRM5_TABLESPACE";

-- DROP TABLE

-- DROP TABLE SW_USER_ACTION;

CREATE TABLE XEDRM5.SW_USER_ACTION (
	USER_ID VARCHAR2(256) NOT NULL,
	WORK_DAY VARCHAR2(20) NULL,
	CLIENT_IP VARCHAR2(20) NULL,
	WATCH_START_DATETIME DATE NULL,
	PROCESS_ID VARCHAR2(20) NULL,
	PROCESS_END_TIME DATE NULL,
	PROCESS_NAME VARCHAR2(20) NULL,
	PROCESS_PATH VARCHAR2(256) NULL,
	CAPTION_NAME VARCHAR2(4000) NULL,
	WEEK NUMBER(3,0) NULL,
	SW_CODE VARCHAR2(30) NULL,
	SW_COMMENT VARCHAR2(4000) NULL,
	RSC_TYPE VARCHAR2(100) NULL,
	DURATION NUMBER(38,0) NULL,
	COMPACT_DATETIME VARCHAR2(20) NOT NULL,
	"YEAR" NUMBER(5,0) NULL
) TABLESPACE "XEDRM5_TABLESPACE";

-- DROP TABLE

-- DROP TABLE SW_WORK;

CREATE TABLE XEDRM5.SW_WORK (
	USER_ID VARCHAR2(256) NOT NULL,
	WORK_DAY VARCHAR2(20) NOT NULL,
	POLICY_ID VARCHAR2(20) NULL,
	WORK_START_TIME VARCHAR2(20) NULL,
	WORK_END_TIME VARCHAR2(20) NULL,
	REAL_START_DATETIME DATE NULL,
	REAL_END_DATETIME DATE NULL,
	WORK_TYPE VARCHAR2(22) NULL,
	WORK_PLACE_ID VARCHAR2(100) NULL,
	OVER_TIMES NUMBER(38,0) NULL,
	DAY_OF_WEEK VARCHAR2(100) NULL,
	LUNCH_START VARCHAR2(100) NULL,
	LUNCH_END VARCHAR2(100) NULL,
	DEPT_ID VARCHAR2(256) NOT NULL,
	IS_ALARM_SEND VARCHAR2(1) NULL,
	"YEAR" NUMBER(38,0) NULL,
	WEEK NUMBER(38,0) NULL,
	TAG VARCHAR2(100) NULL,
	AGENT_INSTALL_YN CHAR(1) NULL,
	HQ_ID VARCHAR2(256) NULL,
	RANK1_PROC_NAME VARCHAR2(256) NULL,
	RANK1_PROC_TIME NUMBER(5,0) NULL,
	RANK2_PROC_NAME VARCHAR2(256) NULL,
	RANK2_PROC_TIME NUMBER(5,0) NULL,
	RANK3_PROC_NAME VARCHAR2(256) NULL,
	RANK3_PROC_TIME NUMBER(5,0) NULL,
	STATUS_ID VARCHAR2(30) NULL,
	WORK_START_CPUTIME NUMBER(38,0) NOT NULL,
	WORK_END_CPUTIME NUMBER(38,0) NOT NULL,
	REAL_START_CPUTIME NUMBER(38,0) NULL,
	REAL_END_CPUTIME NUMBER(38,0) NULL,
	LUNCH_START_CPUTIME NUMBER(38,0) NULL,
	LUNCH_END_CPUTIME NUMBER(38,0) NULL,
	REAL_WORKING_TIME NUMBER(38,0) NULL,
	GOOUT_TIME NUMBER(38,0) NULL,
	CONSTRAINT SW_WORK_PKEY PRIMARY KEY (WORK_DAY, USER_ID)
) TABLESPACE "XEDRM5_TABLESPACE";

-- DROP TABLE

-- DROP TABLE SW_WORK_WEEK;

CREATE TABLE XEDRM5.SW_WORK_WEEK (
	USER_ID VARCHAR2(256) NOT NULL,
	DEPT_ID VARCHAR2(256) NOT NULL,
	"YEAR" VARCHAR2(30) NOT NULL,
	WEEK NUMBER(3,0) NOT NULL,
	WORKING_TIME NUMBER(38,0) NULL,
	OVER_TIME NUMBER(38,0) NULL,
	OUTING_TIME NUMBER(38,0) NULL,
	CLOSED_TIME FLOAT(4) NULL,
	BUSINESS_TRIP_TIME FLOAT(4) NULL,
	AVG_START_TIME VARCHAR2(30) NULL,
	AVG_END_TIME VARCHAR2(30) NULL,
	GO_OUT_TIME NUMBER(38,0) NULL,
	HQ_ID VARCHAR2(256) NULL,
	REAL_WORKING_TIME NUMBER(38,0) NULL,
	AGENT_INSTALL_YN CHAR(1) NULL,
	RANK1_PROC_NAME VARCHAR2(256) NULL,
	RANK1_PROC_TIME NUMBER(5,0) NULL,
	RANK2_PROC_NAME VARCHAR2(256) NULL,
	RANK2_PROC_TIME NUMBER(5,0) NULL,
	RANK3_PROC_NAME VARCHAR2(256) NULL,
	RANK3_PROC_TIME NUMBER(5,0) NULL,
	AWAY_TIME NUMBER(38,0) NULL,
	WORKED_DAYS NUMBER(1,0) NULL,
	CONSTRAINT SW_WORK_WEEK_PKEY PRIMARY KEY (USER_ID, DEPT_ID, YEAR, WEEK)
) TABLESPACE "XEDRM5_TABLESPACE";

-- DROP TABLE

-- DROP TABLE SW_WORKPLACE;

CREATE TABLE XEDRM5.SW_WORKPLACE (
	USER_ID VARCHAR2(256) NOT NULL,
	WORK_PLACE_NM VARCHAR2(20) NOT NULL,
	LATITUDE FLOAT(4) NOT NULL,
	LONGITUDE FLOAT(4) NOT NULL,
	CREATE_DATE DATE NULL,
	WORK_PLACE_ID VARCHAR2(22) NOT NULL,
	ADDRESS VARCHAR2(100) NULL,
	DELETED_YN CHAR(1) NULL,
	CONSTRAINT SW_WORKPLACE_PKEY PRIMARY KEY (WORK_PLACE_ID)
) TABLESPACE "XEDRM5_TABLESPACE";
