# docker-compose.yml

version: "3"

services:
  db-oracle:
      #image: jaspeen/oracle-11g
      #image: jaspeen/oracle-xe-11g
      build:
        context: ../db/oracle/
        dockerfile: Dockerfile
      container_name: oracleHA-database
      restart: always 
      env_file:
        #- ../edm/edm.oracle.env
        - ../db/oracle/oracle.env
      volumes:
        #- oraclexe11gHA:/u01/app/oracle
        - ../db/oracle/script:/docker-entrypoint-initdb.d
      ports:
        - "11521:1521"

  db-postgres:
    image: postgres:13-alpine
    #build:
      #context: ../db/postgres/
      #dockerfile: DockerfileAlpine13
    container_name: postgres13HA-database
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
    volumes:
      #- postgres13HA:/var/lib/postgresql/data
      - ../db/postgres/script:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
        #networks:
        #- backend-postgres
        #nginxHA-postgres:
          #image: nginx

#volumes:
  #oraclexe11gHA:
    #driver: local
    #driver_opts:
      #type: none
      #device: /docker/db/postgres13/data
      #o: bind
