# docker-compose.yml

version: "3"

services:
  db-oracle:
      #image: jaspeen/oracle-11g
      #image: jaspeen/oracle-xe-11g
      build:
        context: ../db/oracle/
        dockerfile: Dockerfile
      container_name: oracleHA-database
      restart: always 
      env_file:
        #- ../edm/edm.oracle.env
        - ../db/oracle/oracle.env
      volumes:
        #- oraclexe11gHA:/u01/app/oracle
        - ../db/oracle/data:/u01/app/oracle
        - ../db/oracle/script:/docker-entrypoint-initdb.d
      ports:
        - "6729:1521"

#volumes:
  #oraclexe11gHA:
    #driver: local
    #driver_opts:
      #type: none
      #device: /docker/db/postgres13/data
      #o: bind
