# docker-compose.yml

version: "3"

services:
  #edm-app-1-postgres: # 서비스명
    #image: zipdrv/edm60:6.1.0.1 # 이미지, 태그
    #build:
      #context: ../edm/
      #dockerfile: Dockerfile
    #ports:
      #- "7080:7080"
    #expose:
      #- "7080"
    #volumes:
      #- /home/whchoi/repo/postEdmHA/data:/app/xedrm60/data
    #env_file:
      #- ../edm/edm.postgres.env
    #depends_on:
      #- db-postgres
    #networks:
      #- backend-postgres
  #edm-app2-1-postgres: # 서비스명
    #image: zipdrv/edm60:6.1.0.1 # 이미지, 태그
    #build:
      #context: ../edm/
      #dockerfile: Dockerfile
    #ports:
      #- "7084:7080"
    #expose:
      #- "7080"
    #env_file:
      #- ../edm/edm.postgres.env
    #volumes:
      #- /home/whchoi/repo/postEdmHA/data:/app/xedrm60/data
    #depends_on:
      #- db-postgres
    #networks:
      #- backend-postgres
  db-postgres:
    image: postgres:13-alpine
    #build:
      #context: ../db/postgres/
      #dockerfile: DockerfileAlpine13
    container_name: postgres13HA-database
    restart: always 
    environment:
      - POSTGRES_PASSWORD=1234
    volumes:
      #- postgres13HA:/var/lib/postgresql/data
      - ../db/postgres/script:/docker-entrypoint-initdb.d
    ports:
      - "7081:5432"
        #networks:
        #- backend-postgres
        #nginxHA-postgres:
          #image: nginx
    #ports:
            #- "7083:80"
        #volumes:
        #- ../nginxLocal/nginx.postgres.conf:/etc/nginx/nginx.conf
    #networks:
      #- backend-postgres
    #depends_on:
      #- db-postgres

#volumes:
  #postgres13HA:
    #driver: local
    #driver_opts:
      #type: none
      #device: /docker/db/postgres13/data
      #o: bind
#networks:
  #backend-postgres:
    #driver: bridge
